### ISSUE TITLE
刚刚好

### ISSUE THREAD

**Issue by MirrorYuChen** [qaz734913414/MNN_FaceTrack#1]
这个应该是前面那个ncnn_facetrack改过来的吧？正好我那个mnn_example差一个人脸跟踪。

**Comment by qaz734913414** [comment]
非常乐意，我看你的那个检测框架功能蛮全的，很期待啊！

**Comment by MirrorYuChen** [comment]
那这两周我抽时间集成一波，感谢老哥为开源社区做的贡献~
